# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/chenwei/Desktop/SingleCPU/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/chenwei/Desktop/SingleCPU/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/chenwei/Desktop [current_project]
add_files C:/Users/chenwei/Desktop/ins_ROM.coe
add_files C:/Users/chenwei/Desktop/data_RAM.coe
add_files C:/Users/chenwei/Desktop/sys_rom.coe
add_files f:/课程/计算机组成原理/Minisys1Av2.2/output/prgmip32.coe
add_files f:/课程/计算机组成原理/Minisys1Av2.2/output/dmem32.coe
add_files -quiet C:/Users/chenwei/Desktop/SingleCPU/project_4.runs/Ins_ROM_synth_1/Ins_ROM.dcp
set_property used_in_implementation false [get_files C:/Users/chenwei/Desktop/SingleCPU/project_4.runs/Ins_ROM_synth_1/Ins_ROM.dcp]
add_files -quiet C:/Users/chenwei/Desktop/SingleCPU/project_4.runs/data_RAM_synth_1/data_RAM.dcp
set_property used_in_implementation false [get_files C:/Users/chenwei/Desktop/SingleCPU/project_4.runs/data_RAM_synth_1/data_RAM.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/display.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/sign_extend.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/selector.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/reg_stack.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/PC.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/IOport.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/InsructionMemory.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/data_selector.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/DataMemory.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/controller.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/ALU.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/Address_decode.v
  C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/sources_1/new/SingleScycleCPU.v
}
read_xdc C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/constrs_1/new/CPU.xdc
set_property used_in_implementation false [get_files C:/Users/chenwei/Desktop/SingleCPU/project_4.srcs/constrs_1/new/CPU.xdc]

synth_design -top SingleScycleCPU -part xc7a100tcsg324-1
write_checkpoint -noxdef SingleScycleCPU.dcp
catch { report_utilization -file SingleScycleCPU_utilization_synth.rpt -pb SingleScycleCPU_utilization_synth.pb }
